export const MoviesData = [
  {
    image: "1_cover.jpg",
    title: "The Last of Us",
    desc: "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
    titleImage: "1_small.jpg",
    category: "Western",
    language: "English",
    year: 2022,
    time: 3,
    video: "",
    rate: 3.4,
  },
  {
    image: "2_cover.jpg",
    title: "Everything Everywhere All at Once",
    desc: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
    titleImage: "2_small.jpg",
    category: "Triller",
    language: "Chinese",
    year: 1999,
    time: 2,
    video: "",
    rate: 5,
  },
  {
    image: "3_cover.jpg",
    title: "Attack on Titan",
    desc: "Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.",
    titleImage: "3_small.jpg",
    category: "Western",
    language: "English",
    year: 2000,
    time: 11,
    video: "",
    rate: 2.5,
  },
  {
    image: "4_cover.jpg",
    title: "The Mandalorian",
    desc: "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
    titleImage: "4_small.jpg",
    category: "Musicals",
    language: "English",
    year: 2022,
    time: 5,
    video: "",
    rate: 1.5,
  },
  {
    image: "5_cover.jpg",
    title: "Luther: The Fallen Sun",
    desc: "A gruesome serial killer is terrorizing London while brilliant but disgraced detective John Luther sits behind bars. Haunted by his failure to capture the cyber psychopath who now taunts him, Luther decides to break out of prison to finish the job by any means necessary.",
    titleImage: "5_small.jpg",
    category: "Romantic",
    language: "English",
    year: 2023,
    time: 7,
    video: "",
    rate: 3.5,
  },
  {
    image: "6_cover.jpg",
    title: "Scream VI",
    desc: "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
    titleImage: "6_small.jpg",
    category: "Horror",
    language: "Swahili",
    year: 2012,
    time: 9,
    video: "",
    rate: 4.5,
  },
  {
    image: "7_cover.jpg",
    title: "The Whale",
    desc: "A reclusive English teacher suffering from severe obesity attempts to reconnect with his estranged teenage daughter for one last chance at redemption.",
    titleImage: "7_small.jpg",
    category: "Fantasy",
    language: "Korean",
    year: 2023,
    time: 4,
    video: "",
    rate: 0,
  },
  {
    image: "8_cover.jpg",
    title: "Shazam! Fury of the Gods",
    desc: 'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
    titleImage: "8_small.jpg",
    category: "action",
    language: "English",
    year: 2020,
    time: 8,
    video: "",
    rate: 0,
  },
  {
    image: "9_cover.jpg",
    title: "A Man Called Otto",
    desc: "When a lively young family moves in next door, grumpy widower Otto Anderson meets his match in a quick-witted, pregnant woman named Marisol, leading to an unlikely friendship that turns his world upside down.",
    titleImage: "9_small.jpg",
    category: "Romantic",
    language: "English",
    year: 2022,
    time: 12,
    video: "",
    rate: 0,
  },
  {
    image: "10_cover.jpg",
    title: "Boston Strangler",
    desc: "Reporters Loretta McLaughlin and Jean Cole bravely pursue the story of the Boston Strangler at great personal risk, putting their own lives on the line in their quest to uncover the truth.",
    titleImage: "10_small.jpg",
    category: "science",
    language: "English",
    year: 2022,
    time: 6,
    video: "",
    rate: 0,
  },
];
