export const UserData = [
  {
    fullname: "Andy Serkis",
    image: "Andy_Serkis.jpeg",
    rating: 1,
    created_At: "21 June 2022",
    email: "andy@gmail.com",
  },
  {
    fullname: "Anthony Mackie",
    image: "Anthony_Mackie.jpeg",
    rating: 2,
    created_At: "21 June 2022",
    email: "anthony@gmail.com",
  },
  {
    fullname: "Brandon T Jackson",
    image: "Brandon_T_Jackson.jpg",
    rating: 3,
    created_At: "21 June 2022",
    email: "brandon@gmail.com",
  },
  {
    fullname: "Elijah Wood",
    image: "Elijah_Wood.jpeg",
    rating: 4,
    created_At: "21 June 2022",
    email: "elijah@gmail.com",
  },
  {
    fullname: "Ian McKellen",
    image: "Ian_McKellen.jpeg",
    rating: 5,
    created_At: "21 June 2022",
    email: "ian_mck@gmail.com",
  },
  {
    fullname: "Karl Urban",
    image: "Karl_Urban.jpeg",
    rating: 3.6,
    created_At: "21 June 2022",
    email: "karl@gmail.com",
  },
  {
    fullname: "Leah Jeffries",
    image: "Leah_Jeffries.jpeg",
    rating: 4.5,
    created_At: "21 June 2022",
    email: "leah@gmail.com",
  },
  {
    fullname: "Letitia Wright",
    image: "Letitia_Wright.jpeg",
    rating: 1.8,
    created_At: "21 June 2022",
    email: "Letitia@gmail.com",
  },
  {
    fullname: "Paul Walker",
    image: "Paul_Walker.jpeg",
    rating: 2.5,
    created_At: "21 June 2022",
    email: "paul@gmail.com",
  },
];
