export const videos = [
  {
    adult: false,
    backdrop_path: "/6ZZjNFjTlO9F25467CruIibwuxl.jpg",
    id: 739405,
    title: "Operation Fortune: Ruse de Guerre",
    original_language: "en",
    original_title: "Operation Fortune: Ruse de Guerre",
    overview:
      "Special agent Orson Fortune and his team of operatives recruit one of Hollywood's biggest movie stars to help them on an undercover mission when the sale of a deadly new weapons technology threatens to disrupt the world order.",
    poster_path: "/vQGw9lzfh9hEoYSOWAE5XbZ6J7s.jpg",
    media_type: "movie",
    genre_ids: [28, 53, 35],
    popularity: 217.47,
    release_date: "2023-01-04",
    video: false,
    vote_average: 6.745,
    vote_count: 194,
  },
  {
    adult: false,
    backdrop_path: "/oCKZAdUROqdlTcUOstqJ1gM8JQt.jpg",
    id: 615777,
    title: "Babylon",
    original_language: "en",
    original_title: "Babylon",
    overview:
      "A tale of outsized ambition and outrageous excess, tracing the rise and fall of multiple characters in an era of unbridled decadence and depravity during Hollywood's transition from silent films and to sound films in the late 1920s.",
    poster_path: "/wjOHjWCUE0YzDiEzKv8AfqHj3ir.jpg",
    media_type: "movie",
    genre_ids: [18, 35],
    popularity: 310.377,
    release_date: "2022-12-22",
    video: false,
    vote_average: 7.573,
    vote_count: 1402,
  },
  {
    adult: false,
    backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
    id: 505642,
    title: "Black Panther: Wakanda Forever",
    original_language: "en",
    original_title: "Black Panther: Wakanda Forever",
    overview:
      "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    media_type: "movie",
    genre_ids: [28, 12, 878],
    popularity: 1938.36,
    release_date: "2022-11-09",
    video: false,
    vote_average: 7.325,
    vote_count: 4156,
  },
  {
    adult: false,
    backdrop_path: "/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg",
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    original_language: "en",
    original_title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    media_type: "movie",
    genre_ids: [16, 12, 35, 10751],
    popularity: 2909.592,
    release_date: "2022-12-07",
    video: false,
    vote_average: 8.4,
    vote_count: 4675,
  },
  {
    adult: false,
    backdrop_path: "/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
    id: 677179,
    title: "Creed III",
    original_language: "en",
    original_title: "Creed III",
    overview:
      "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damien Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damien — a fighter who has nothing to lose.",
    poster_path: "/vJU3rXSP9hwUuLeq8IpfsJShLOk.jpg",
    media_type: "movie",
    genre_ids: [18],
    popularity: 1167.291,
    release_date: "2023-03-01",
    video: false,
    vote_average: 7.08,
    vote_count: 363,
  },
  {
    adult: false,
    backdrop_path: "/qzSjrYSZAWrjhg6Yf3hCcfJE4o0.jpg",
    id: 85720,
    name: "Shadow and Bone",
    original_language: "en",
    original_name: "Shadow and Bone",
    overview:
      "In a world cleaved in two by a massive barrier of perpetual darkness, a young soldier uncovers a power that might finally unite her country. But as she struggles to hone her power, dangerous forces plot against her. Thugs, thieves, assassins and saints are at war now, and it will take more than magic to survive.",
    poster_path: "/mS9O9mjPlwpLTne4JgQlDkgREWA.jpg",
    media_type: "tv",
    genre_ids: [18, 10765],
    popularity: 372.739,
    first_air_date: "2021-04-23",
    vote_average: 8.077,
    vote_count: 1003,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
    id: 76600,
    title: "Avatar: The Way of Water",
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    media_type: "movie",
    genre_ids: [878, 12, 28],
    popularity: 1124.883,
    release_date: "2022-12-14",
    video: false,
    vote_average: 7.73,
    vote_count: 5779,
  },
  {
    adult: false,
    backdrop_path: "/A5JyEZvXHbPLN2cU65oB9NaIuYH.jpg",
    id: 768362,
    title: "Missing",
    original_language: "en",
    original_title: "Missing",
    overview:
      "When her mother disappears while on vacation in Colombia with her new boyfriend, June’s search for answers is hindered by international red tape. Stuck thousands of miles away in Los Angeles, June creatively uses all the latest technology at her fingertips to try and find her before it’s too late. But as she digs deeper, her digital sleuthing raises more questions than answers... and when June unravels secrets about her mom, she discovers that she never really knew her at all.",
    poster_path: "/jYXJW19PMEUrpyavEHrnnlItQn1.jpg",
    media_type: "movie",
    genre_ids: [18, 9648, 53],
    popularity: 127.424,
    release_date: "2023-01-19",
    video: false,
    vote_average: 7.62,
    vote_count: 163,
  },
];
